version: '3.5'

# docker stack deploy --compose-file stack-invoiceplane.yml invoiceplane

volumes:
  invoiceplane_data:
  mariadb_10_4:

services:
  proxyv2:
    image: traefik:v2.5 # The official Traefik docker image
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "8092:80"     # The HTTP port
      - "4432:443"   # The HTTP port
      - "8182:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    labels:
      - "traefik.enable=false"
  invoiceplane:
    image: mhzawadi/invoiceplane:dev
    volumes:
      - invoiceplane_data:/var/www/html/uploads
    environment:
      - TZ=utc
      - MYSQL_HOST=mariadb_10_4
      - MYSQL_USER=InvoicePlane
      - MYSQL_PASSWORD=invoiceplane
      - MYSQL_DB=InvoicePlane
      - IP_URL=http://invoiceplane.docker.local
      - DISABLE_SETUP=false
    labels:
      - "traefik.http.routers.invoiceplane.rule=Host(`invoiceplane.docker.local`)"
      - "traefik.http.routers.invoiceplane.service=invoiceplane"
      - "traefik.http.services.invoiceplane.loadbalancer.server.port=8092"
  mariadb_10_4:
    # MySQL 5.7
    image: mariadb:10.4.10
    volumes:
      - mariadb_10_4:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_password
      - MYSQL_DATABASE=InvoicePlane
      - MYSQL_USER=InvoicePlane
      - MYSQL_PASSWORD=invoiceplane
    labels:
      - "traefik.enable=false"